### ISSUE TITLE
SW Kotor 1 DLL in injected but hotkeys don't work

### ISSUE THREAD

**Issue by odt1** [Hirtol/speedhack-rs#2]
Console output shows that ddl is loaded, can reload config, but any SH hotkeys are plain not working.

**Comment by Hirtol** [comment]
Try the newest release, that was an issue I fixed a bit ago but didn't make a new release for.

Let me know if it works.

**Comment by odt1** [comment]
it's working now, thank you for this amazing hack! <3

**Comment by Hirtol** [comment]
Glad it's fixed for you!
